config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'products#index'
  get "/search" => 'products#search'

  resources :specials
  resources :versions

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :products_versions
  has_many :versions, through: :products_versions
  has_many :specials, through: :versions
end

app/models/products_version.rb
class ProductsVersion < ActiveRecord::Base
  belongs_to :product
  belongs_to :version
end

app/models/special.rb
class Special < ActiveRecord::Base
  has_many :versions
end

app/models/version.rb
class Version < ActiveRecord::Base
  belongs_to :special
  has_many :products_versions
  has_many :products, through: :products_versions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    @product = Product.find params[:id]
    cloned_attrs = @product.attributes
    cloned_attrs.delete("id")

    @cloned_product = Product.create cloned_attrs
    @cloned_product.update product_params

    #cheating a bit here. In your app you will be editing
    #a product (scenario) in the context of a special (sheet)
    #so that specific sheet would need to be passed in and
    #initialized here
    special = @product.specials.first

    #create a new version for each special that product belongs to
    new_version = special.versions.create

    #cheating here too.  This would either be the most recent
    #version, or the specific version being used when the
    #scenario was "edited"
    v = special.versions.first
    new_version.products << (v.products - [@product])
    new_version.products << @cloned_product

    redirect_to specials_path
  end

  def product_params
    params.require(:product).permit(:name)
  end

  def search
    #surrounding the query with percent signs so when we use it
    #in a "LIKE" query the database will match the query regardless
    #of where it appears in the text value of the given field
    formatted_query = "%#{params[:query]}%"

    if params[:query].to_i != 0
      @products = Product.where(id: params[:query])
    else
      @products = Product.where("name like ? or description like ?", formatted_query, formatted_query)
    end

    render json: @products
  end
end

app/controllers/specials_controller.rb
class SpecialsController < ApplicationController
  def index
    @specials = Special.all
  end

  def show
    @special = Special.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LiveSearchExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
<%= yield %>
</div>

</body>
</html>

app/views/products/_product.html.erb
<div class="product">
  <p>id: <%= product.id %></p>
  <p>name: <%= product.name %></p>
  <p>description: <%= product.description %></p>
</div>

app/views/products/edit.html.erb
<%= form_for @product do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
<h1> Pet store </h1>

<div id="search-wrapper">
  <input id="search" type="text" placeholder="search">
</div>

<div id="products">
  <%= render @products %>
</div>

app/views/specials/_special.html.erb
<div>
  <%= link_to special.name, special_path(special) %>
</div>

app/views/specials/index.html.erb
<%= render @specials %>

app/views/specials/show.html.erb
<% @special.versions.each do |v| %>
  <div>
    <%= v.products.map{|p| "#{p.id}: #{p.name}"}.join(",") %>
  </div>
<% end %>